---
title: 'Error checks'
output: pdf_document
classoption: landscape
author: Sasha D. Hafner
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

# File and directory names

```{r}
print(i)
print(j)
```

# Emission `emis` check

```{r}
d <- dat[[i]][[j]]$emis
```
## Plots
```{r}
library(ggplot2)
ggplot(d, aes(ct, e.rel, colour = cpmid)) + geom_line() + geom_point() + theme(legend.position = 'none')
ggplot(d, aes(t.start, e.rel, colour = cpmid)) + geom_line() + geom_point() + theme(legend.position = 'none')
```

## Summary and missing values

```{r}
print(summary(d))
print(apply(d, 2, function(x) sum(is.na(x))))

# Missing incorporation times
table(d$incorp, d$time.incorp, exclude = NULL)
x <- subset(d, incorp %in% c('deep', 'shallow') & is.na(time.incorp))
unique(as.character(x$file))
x[, c('file','row.in.file.int','institute')]

# Problems with application start time, was problem in the merge of d1 and d2
# Should be POSIXct/POSIXt
class(d$app.start)

# Wind heights in wrong units
# Should be in m
# Expected values maybe 0.1 - 10 m
summary(d$wind.z)
range(na.omit(d$wind.z))
x <- subset(d, wind.z>15)
nrow(x)
unique(as.character(x$file))
unique(x[,c('file','row.in.file.int','institute')])
unique(x[,c('file','institute')])

# Air temperature heights
# Also in m now
# Expected values perhaps 0.1 - 10 m
summary(d$air.temp.z)
range(na.omit(d$air.temp.z))
x <- subset(d, air.temp.z>10)
nrow(x)
unique(as.character(x$file))
unique(x[,c('file','row.in.file.int','institute')])
unique(x[,c('file','institute')])

# Why are there zeroes?
x <- subset(d, air.temp.z == 0)
nrow(x)
unique(as.character(x$file))
unique(x[,c('file', 'row.in.file.int', 'institute', 'air.temp.z', 'air.temp')])
unique(x[,c('file', 'institute', 'air.temp.z')])
# Not sure, but there they are all in ALFAM1. Leaving as-is

# Measurement techniques
# There should be zero NAs!
as.character(unique(d$meas.tech))
table(d$meas.tech, exclude = NULL)
sum(is.na(d$meas.tech))
x <- subset(d, is.na(meas.tech))
unique(x[,c('row.in.file.int','institute')])

# Blank method
x <- unique(d[,c('file','institute','meas.tech','row.in.file.int')])
subset(x,meas.tech=='')

# Emission measurements before application time (app.start)
x <- subset(d,t.start < app.start)
x <- x[order(x$file, x$row.in.file.int),]
dim(x)
x[,c('file','row.in.file.int', 't.start', 't.end', 'app.start', 'ct', 'field','plot', 'tan.app', 'j.NH3')]
# These are cases where emission was measured before application
# As long as emission is clearly low and ct < 0, there is no indication of a problem
# For Swiss data at end, application occurred within the first interval
# Similar for SDU--apparently application was after the passive samplers were set out

# Negative interval duration dt
x <- subset(d, dt < 0)
dim(x)
x[,c('file','row.in.file.int', 't.start', 't.end', 'app.start', 'dt', 'ct', 'field','plot', 'tan.app', 'j.NH3')]

# Negative cta
x <- subset(d, cta < 0)
head(x[,c('file','row.in.file.int', 't.start', 't.end', 'app.start', 'dt', 'ct', 'field','plot', 'tan.app', 'j.NH3')])
unique(x$plot)

# Gaps, missing measurement intervals
d$dcta <- c(0, diff(d$cta))
d$dcta[d$interval == 1] <- d$dcta
x <- d[signif(d$dcta, 3) != signif(d$dt, 3), ]
x[, c('file','row.in.file.int', 'interval', 'dt', 'ct', 'dcta', 'field','plot')]

x <- d[abs(log10(signif(d$dcta, 3)/signif(d$dt, 3))) > 0.2, ]
x[, c('file','row.in.file.int', 'interval', 'dt', 'ct', 'dcta', 'field','plot')]

# Duplicated shifts
# Should be none
s <- ddply(d, 'cpmid', summarise, n.int.duplicates = sum(duplicated(interval)))
x <- subset(s, n.int.duplicates > 1)
x
y <- subset(d, cpmid == x$cpmid)
y[, c('file', 'institute', 'row.in.file.int', 'plot', 'rep')]

hist(d$dt - d$dt.calc, xlim = c(-0.5, 0.5), breaks = 1000)
quantile(d$dt - d$dt.calc)

# Shift time mismatches
# Should be none
y <- d[order(d$cpmid, d$interval), ]
# Problem when one shift ends after the next begins
y$problem <- c(y$cpmid[-nrow(y)] == y$cpmid[-1] & y$t.end[-nrow(y)] > y$t.start[-1], NA)
y$overlap <- c(as.numeric(difftime(y$t.end[-nrow(y)], y$t.start[-1], units = 'hours')), NA)
x <- subset(y, problem)
x[, c('file', 'institute', 'row.in.file.int', 'plot', 't.start', 't.end', 'interval', 'j.NH3', 'overlap')]

## Very short sets
#x <- subset(ds, n.ints < 4)
#dim(x)
#y <- subset(d, cpmid %in% x$cpmid)
#y <- y[order(y$institute, y$row.in.file.int), ]
#dim(y)
#y[, c('file', 'inst', 'institute', 'row.in.file.int', 'plot', 'cpmid', 't.start', 't.end', 'ct', 'interval', 'j.NH3')]
#
## High relative emission
#x <- subset(ds, e.rel.final>1)
#dim(x)
#x[, c('file', 'inst', 'institute', 'first.row.in.file.int', 'plot', 'cpmid', 'tan.app', 'e.rel.final', 'e.rel.48')]

# Problems with incorporation
# In make_database.R NAs are set to 'None',  so problems will not show up here. Need to check this
y <- subset(d, is.na(incorp) | incorp=='')
dim(y)
y <- y[order(y$institute, y$row.in.file.int), ]
y <- rounddf(y)
y

# Missing locations
x <- subset(d, is.na(d$lat)|is.na(d$long))
x <- data.frame(file=unique(x$file))
x

# Missing slurry type
x <- subset(d, is.na(man.source))
unique(x$institute)
unique(x[, c('institute', 'man.source')])
x

# These all are probably measurements made with no application or prior to application
# Need to remove from database if the latter
# Missing application method
x <- subset(d, is.na(app.method))
unique(x$institute)
x <- subset(d, is.na(app.method) & man.source != 'none')
names(x)
x[, c('institute', 'file', 'row.in.file.int', 'app.method', 'app.rate', 'man.source')]
x

# Missing soil type
x <- subset(d, is.na(soil.type))
unique(x$institute)
unique(x[, c('institute', 'soil.type')])
x

# Missing crop
# Only with no manure for INRA, plus many for SDU
x <- subset(d, is.na(crop))
unique(x$institute)
unique(x[, c('institute', 'crop', 'man.source')])
x[, c('institute', 'file', 'row.in.file.int', 'crop')]

x <- subsetd(d, dt == 0)
dim(x)

# Rel humidity and air.temp zero too often, are they missing values?
x <- subsetd(d, air.temp == 0)
dim(x)

# Some heights seem to be a mix of cm and m
names(d)[grepl('\\.z', names(d))]

# Everything should be in m now
sort(unique(d$air.temp.z))
sort(unique(d$soil.temp.z))
sort(unique(d$wind.z))

# Except crop height
sort(unique(d$crop.z))
 
```
