---
title: 'Summary of new ALFAM2 data'
output: pdf_document
author: Sasha D. Hafner
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r}
pdat[, digested := grepl('anaerobic digestion', tolower(paste(man.trt1, man.trt2)))]
```


```{r}
dim(pdat)
length(unique(pdat$pmid))
length(unique(pdat$pid))
```

```{r}
dim(idat)
```

```{r}
table(pdat$sub.period)
table(country = up$country, sub.period = up$sub.period)
table(institute = up$institute, sub.period = up$sub.period)
```

```{r}
table(pdat$man.trt1)
table(pdat$man.trt2)
```

```{r}
table(pdat$man.source)
```

```{r}
table(pdat[, c('meas.tech')])
table(pdat[, c('meas.tech', 'meas.tech2')])
```

```{r}
table(pdat[, c('app.method')], exclude = NULL)
table(pdat[, c('app.method.orig', 'app.method')], exclude = NULL)
```

```{r}
table(upl$country)
```

```{r}
table(pdat$meas.tech)
table(pdat$meas.tech.orig)
table(pdat$meas.tech2)
```

Acidification table.

```{r}
acidtab <- table(paste(pdat$man.trt1, pdat$man.trt2, pdat$man.trt3, sep = ', '), pdat$acid)
acidtab <- acidtab[order(-acidtab[, 'TRUE']), ]
acidtab
```

```{r}
trttab <- table(pdat$treat, pdat$acid)
trttab <- trttab[order(-trttab[, 'TRUE']), ]
trttab
```

```{r}
unique(pdat[, c('inst', 'institute', 'country')])
```

```{r}
table(pdat[, c('institute', 'app.method')], exclude = NULL)
table(pdat[, c('sub.period', 'app.method')], exclude = NULL)
table(pdat[, c('corr.period', 'app.method')], exclude = NULL)
```


