---
title: 'Summary of new ALFAM2 data'
output: pdf_document
author: Sasha D. Hafner
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r}
pdat$digested <- grepl('anaerobic digestion', tolower(paste(pdat$man.trt1, pdat$man.trt2)))
```


```{r}
dim(pdat)
length(unique(pdat$pmid))
length(unique(pdat$pid))
```


```{r}
up <- pdat[unique(pdat$pid), ]
table(pdat$sub.period)
table(up$sub.period)
table(country = up$country, sub.period = up$sub.period)
table(institute = up$institute, sub.period = up$sub.period)
```

```{r}
table(pdat$pdat$man.trt1)
table(pdat$man.trt2)
```

```{r}
u3 <- subset(pdat, sub.period == 3)
up3 <- subset(up, sub.period == 3)
table(paste(u3$sub.period, u3$country, u3$institute, u3$man.source, u3$meas.tech2), u3$digested)
table(u3$digested)
table(up3$digested)
```

```{r}
table(u3$meas.tech2)
table(up3$meas.tech2)
```

```{r}
table(up3$country)
table(u3$country)
```

Acidification table.

```{r}
acidtab <- table(paste(pdat$man.trt1, pdat$man.trt2, pdat$man.trt3), pdat$acid)
acidtab <- acidtab[order(-acidtab[, 'TRUE']), ]
acidtab
```

```{r}
trttab <- table(pdat$treat, pdat$acid)
trttab <- trttab[order(-trttab[, 'TRUE']), ]
trttab
```

```{r}
unique(pdat[, c('inst', 'institute', 'country')])
```


